
name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create env.properties file
      run: |
        mkdir -p src/main/resources/env.properties
        echo "NEO4J_URI=${{secrets.NEO4J_URI}}" >> env.properties
        echo "NEO4J_USERNAME=${{secrets.NEO4J_USERNAME}}" >> env.properties
        echo "NEO4J_PASSWORD=${{secrets.NEO4J_PASSWORD}}" >> env.properties
        echo "GEMINI_API_KEY=${{secrets.GEMINI_API_KEY}}" >> env.properties


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
